# -*- coding: utf-8 -*-
from odoo import models, fields
from odoo import Command
from datetime import date
from odoo.tools import date_utils
from odoo.exceptions import UserError

class Move(models.Model):
    """to inherit the invoicing template"""
    _inherit = "account.move"
    student_id = fields.Many2one('student.details',
                                 string="Student")
    room_id = fields.Many2one('hostel.room',string="Room",
                              readonly=True)
    cron_generated=fields.Boolean(string="Cron",default=False)

    def action_post(self):
        """to post the invoice manually"""
        today=date.today()
        # day=date.today()
        # month=day.strftime('%m')
        get_month= date_utils.get_month(today)

        for invoice in self:
            existing = self.search([
                ('student_id', '=', invoice.student_id.id),
                ('cron_generated', '=', True),
                ('state', '=', 'posted'),
                ('invoice_date', '=', get_month),
                ('id', '!=', invoice.id),
            ], limit=1)
            print(existing)

            if existing:
                raise UserError(
                    "The monthly hostel invoice has already been generated by the cron for this student."
                )
        res = super().action_post()

        template = self.env.ref('hostel_management.invoice_email_template')

        for invoice in self:
            if invoice.student_id and invoice.student_id.email:
                email_values = {
                    'email_to': invoice.student_id.email,
                    'email_from': self.env.user.email,
                }
                template.send_mail(
                    invoice.id,
                    force_send=True,
                    email_values=email_values
                )

        return res

    def _send_monthly_invoice(self):
        """to post invoice automatically"""
        students = self.env['student.details'].search([
            ('room_id', '!=', False),
            ('email', '!=', False)
        ])

        product = self.env.ref(
            'hostel_management.rental_product1',
            raise_if_not_found=False
        )

        if not product:
            return

        for student in students:
            invoice = self.env['account.move'].create({
                'move_type': 'out_invoice',
                'partner_id': student.partner_id.id,
                'student_id': student.id,
                'room_id': student.room_id.id,
                'cron_generated': True,
                # 'invoice_line_ids': [(0, 0, {
                #     'product_id': product.id,
                #     'quantity': 1,
                #     'price_unit': student.room_id.rent,
                'invoice_line_ids': [Command.create({
                    'product_id': product.id,
                    'quantity': 1,
                    'price_unit': student.room_id.rent,

                })],
            })

        invoice.action_post()
